### ISSUE TITLE
Generate YAML file

### ISSUE THREAD

**Issue by ghost** [aaronpowell/azure-functions-nodejs-openapi#13]
Hi...

Is there an option to be able to generate the json or yaml file from a cli command?

The idea is to generate the file locally, (during development) or during build process on the pipelines, and have the yaml file ready to be supplied to apim.

Is this possible?

**Comment by aaronpowell** [comment]
Unfortunately not. Due to the way Azure Functions operates, the Functions available are not known until runtime, as it requires a lot of parsing and loading of the script files. The only way that a CLI could do it is to essentially run the Functions host itself and then extract the metadata.

There's a new Functions programming model being developed (see https://github.com/Azure/azure-functions-nodejs-worker/issues/480) that may open up some better options for OpenAPI support, but at the moment there's not a lot more I can do.
